id: P624CD526
initial_creation_type: ocr
source_metadata:
  volumes:
    c3ac938fbb3746d9b8d983b60afe6953:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: དབྱུག་པ་གཤིན་རྗེ་གཤེད་རྣམ་པར་འཇོམས་པ་ཞེས་བྱ་བའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
